CREATE TABLE `anonbook`.`posts` (
  `id` INT NOT NULL,
  `date` DATETIME(6) NULL DEFAULT NULL,
  `image` VARCHAR(225) NULL DEFAULT NULL,
  `text` VARCHAR(225) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
